require 'shellwords'

task default: %i[ruby]

task ruby: ['ruby:tests']

namespace :ruby do
  task tests: %i[test_rails test_sinatra test_jekyll]

  task :test_rails do
    rails_tests_file = File.join(__dir__, 'tc_rails.rb')
    ruby Shellwords.escape(rails_tests_file)
  end

  task :test_sinatra do
    sinatra_tests_file = File.join(__dir__, 'tc_sinatra.rb')
    ruby Shellwords.escape(sinatra_tests_file)
  end

  task :test_jekyll do
    jekyll_tests_file = File.join(__dir__, 'tc_jekyll.rb')
    ruby Shellwords.escape(jekyll_tests_file)
  end
end
